@startuml
'https://plantuml.com/component-diagram
skinparam componentStyle rectangle

component Clone #lightyellow [
  Clone(this) = let
    State(data) = ...
  within
    State(empty)
]

component "Clone(1)" as Clone1 #lightyellow
component "Clone(2)" as Clone2 #lightyellow
component "Clone(3)" as Clone3 #lightyellow

Clone1 --> [RemoteTransmit(1,2)] : send.1.2...
Clone1 --> [RemoteTransmit(1,3)] : send.1.3...
Clone2 --> [RemoteTransmit(2,1)] : send.2.1...
Clone2 --> [RemoteTransmit(2,3)] : send.2.3...
Clone3 --> [RemoteTransmit(3,1)] : send.3.1...
Clone3 --> [RemoteTransmit(3,2)] : send.3.2...

[RemoteTransmit(1,2)] --> Clone2 : receive.1.2...
[RemoteTransmit(1,3)] --> Clone3 : receive.1.3...
[RemoteTransmit(2,1)] --> Clone1 : receive.2.1...
[RemoteTransmit(2,3)] --> Clone3 : receive.2.3...
[RemoteTransmit(3,1)] --> Clone1 : receive.3.1...
[RemoteTransmit(3,2)] --> Clone2 : receive.3.2...

@enduml