@startuml
'https://plantuml.com/sequence-diagram
hide footbox

box Alice's device
control "app" as proc1
database "clone" as genesis << genesis >>
end box

proc1 -> proc1: Authenticate Alice
proc1 -> genesis **: init ""domain.ex.org""
note left
Configuration includes domain secret "abcd"
end note
genesis -> messaging : connect
genesis -> messaging : init domain channel

proc1 --> genesis: install statutes &\nagreements ontology

proc1 -> genesis ++: Op0 ≪transaction≫
rnote left
<code>
[{
  "@id": "domain.ex.org",
  "mld:access": "mld:Permission",
  "mld:secret": "abcd"
}, {
  "@id": "Alice",
  "@type": "mld:Principal",
  "mld:certificate": "1234",
  "mld:hasPermission": [{
    "@type": "mld:Authority",
    "mld:controlledShape": {
      "@id": "AllSubjects",
      "@type": "sh:NodeShape"
    }
  }]
}, {
  "@id": "Bob",
  "@type": "mld:Principal",
  "mld:certificate": "5678"
}, {
  "@id": "mld:accessControlStatute",
  "mld:sufficientCondition": {
    "@id": "mld:hasAuthority"
  }
}]
</code>
(declares access control is by whitelist ACL)
end note

rnote over genesis
Op0 allowed because no
access control is in place
end note

genesis -> messaging: Op0 ≪agree≫
genesis --> proc1: //resolve//
genesis -> proc1 --: Op0 ≪update≫
messaging ->x] : Op0

@enduml