@startuml
'https://plantuml.com/sequence-diagram
hide footbox

database "Alice's clone" as genesis
box Bob's device
control "app" as proc2
database "clone" as clone2
end box

proc2 -> proc2: Authenticate Bob
proc2 -> clone2 **: start on ""domain.ex.org""

clone2 -> messaging : connect
clone2 -> genesis ++: snapshot request
note left
signed with Bob's private key
end note
rnote over genesis
check Bob read access → OK
end note
genesis -> clone2 --: snapshot
clone2 -> messaging : connect domain channel

rnote over proc2: ""INSERT"" //[anything]//
proc2 -> clone2 ++: Op1 ≪transaction≫

clone2 -> clone2: ACL constraint check

clone2 --> proc2 --: //reject: unauthorised//

@enduml