@startuml
'https://plantuml.com/sequence-diagram
hide footbox
autonumber

database "Alice's clone" as genesis
box Bob's device
control "app" as proc2
database "clone" as clone2
end box

genesis -> messaging: Op3 ≪agree≫
rnote left
<code>
{
  "@delete": {
    "@id": "Bob",
    "mld:hasPermission": {
      "mld:appliesToPattern": { "@id": "?" }
    }
  }
}
(deletes Bob's write permission)
end note

note over messaging
Op3 is delayed
end note

proc2 -> clone2 ++: Op4 ≪transaction≫
rnote left: ""INSERT"" //[anything]//

clone2 -> clone2: ACL constraint check

clone2 -> messaging: Op4
clone2 --> proc2: //resolve//
clone2 -> proc2 --: Op4 ≪update≫

messaging -> clone2 ++: Op3
note left: Op3 agreement pre-dates Op4
clone2 -> proc2 ++: Fork or Void?
proc2 --> clone2 --: Void
clone2 -> clone2: Void Op4
note over clone2: Op4 also removed from Journal
clone2 -> clone2: Apply Op3
clone2 -> proc2 --: Op3 - Op4 ≪update≫

messaging -x genesis : Op4
note left: Ignore: op pre-dates agreement

@enduml