@startuml
'https://plantuml.com/object-diagram
hide circle

skinparam object {
  BackgroundColor Pink
}

package mld {

class AgreementCondition <<statutory>> <<extension point>>

abstract class Principal <<extension point>>
note right
gives access
to the domain
end note
class PkiPrincipal {
  certificate : String
}
PkiPrincipal --|> Principal

class Authority
note left
Authority is permission
to unilaterally agree.
---
A "lock" is just temporary
exclusive authority.
end note
object hasAuthority
hasAuthority --> AgreementCondition : rdf:type
hasAuthority ..> Authority : <<require>>
Permission "*" <--o Principal : hasPermission

abstract class Permission <<statutory>>
Permission --|> AccessControl

class WritePermission {
  controlledShape : sh:NodeShape
}
Authority --|> WritePermission
WritePermission --|> Permission

class RaftConsensus {
  mtbf : float
  electionTimeout : float
  broadcastTime : float
}
RaftConsensus --|> AgreementCondition

abstract class External
External --|> AgreementCondition

object "[domain]" as domain {
  secret = "abcd"
}

abstract class AccessControl <<statutory>> <<extension point>>
domain ..> AccessControl : <<statutory>>\naccess
note on link
added by the app
to specify use of
e.g. Permissions
end note

}
@enduml
