@startuml
'https://plantuml.com/object-diagram
hide circle

skinparam object {
  BackgroundColor Pink
}

package mld {

class AgreementCondition <<statutory>> <<extension point>>

class Principal {
  publicKey : String
}

class Authority
note left
Authority is permission
to unilaterally agree.
---
A "lock" is just
temporary authority.
end note
object hasAuthority
hasAuthority --> AgreementCondition : rdf:type
hasAuthority ..> Authority : <<require>>
Permission "*" <--o Principal : hasPermission

abstract class Permission
Permission --|> AccessControl

class WritePermission {
  appliesToPattern : json-rql
}
Authority --|> WritePermission
WritePermission --|> Permission

object readPermission
note left
gives access
to the domain
end note
readPermission --> Permission : rdf:type

class RaftConsensus {
  mtbf : float
  electionTimeout : float
  broadcastTime : float
}
RaftConsensus --|> AgreementCondition

abstract class External
External --|> AgreementCondition

object "[domain]" as domain {
  secret = "abcd"
}

abstract class AccessControl <<statutory>> <<extension point>>
domain ..> AccessControl : <<statutory>>\naccess
note on link
added by the app
to specify use of
e.g. Permissions
end note

}
@enduml
