@startuml
'https://plantuml.com/class-diagram
hide circle

skinparam object {
  BackgroundColor Pink
}

class "[rdfs:Class]" as class {
[rdfs:Property] : [rdfs:range | literal]
}
object "[subject]" as subject {
[property] = [object]
}
subject --> class : [property]
note on link
links to Class,
not instance
end note
class o--> "[rdfs:range | Class]" : [rdfs:Property]
class --|> "[Superclass]" : rdfs:SubClassOf

@enduml