@startuml
'https://plantuml.com/class-diagram
hide circle

skinparam object {
  BackgroundColor Pink
}

package "[package prefix]" {

class "[rdfs:Class]" as class {
[rdfs:Property] : [rdfs:range : literal]
}
note right of class::[rdfs:Property]
Literal properties
are defined inline
end note
object "[subject]" as subject {
[property] = [object]
}
subject --> subject : [property]
note on link
Properties are
defined inline,
or with a link to
another subject
end note
subject --> class : rdf:type
class o--> "[rdfs:range : Class]" : [rdfs:Property]
note on link
A UML aggregation
is used to define
the ID and range
of a link property
end note
class --|> "[Superclass]" : rdfs:SubClassOf
note on link
A superclass link
has this form but
will not be labelled
end note

}
@enduml