@startuml
'https://plantuml.com/object-diagram

hide circle

skinparam object {
  BackgroundColor Pink
}

package mld {

class Statute <<extension point>> {
  statutoryClass : rdfs:Class [0..*]
  statutoryProperty : rdf:Property [0..*]
  statutoryUpdateVerb: 'DELETE' | 'INSERT' [1..2]
}
note bottom
Defines a scope of data requiring agreement.
In other diagrams we'll use the <<statutory>>
stereotype for statutory classes and properties.
end note
note right of Statute::statutoryClass
A class is statutory if a
statutoryClass exists for it.
end note
note right of Statute::statutoryProperty
A property is statutory if
a statutoryProperty exists.
end note
note right of Statute::statutoryUpdateVerb
Is agreement required on
delete, insert or both?
end note

Statute o--> "*" AgreementCondition : sufficientCondition

object statuteStatute
note top
Statutes and agreement
conditions are themselves
statutory.
end note
statuteStatute --> Statute : statutoryClass
statuteStatute --> Statute : rdf:type
statuteStatute --> AgreementCondition : statutoryClass

object rdfsStatute {
  statutoryClass = rdfs:Class
  statutoryClass = rdf:Property
  statutoryProperty = rdf:type
}
note top
  Classes, property definitions
  and the type of every subject
  is statutory.
end note
rdfsStatute --> Statute : rdf:type

object accessControlStatute {
  statutoryClass = AccessControl
  statutoryProperty = access
}
note top
  Choice of access control
  mechanism is statutory.
end note
accessControlStatute --> Statute : rdf:type

}
@enduml
