@startuml
'https://plantuml.com/class-diagram
hide circle

package App {
  class MeldUpdate {
    @delete : GraphSubject [*]
    @insert : GraphSubject [*]
    @tick : integer
    @principal : Reference
    @agree
    trace(rel): (EncodedOperation, Attribution) [*]
  }
  note top of MeldUpdate
    App-visible update. Algorithmically built
    from operations by local m-ld engine.
  end note

  note left of MeldUpdate::principal
    The principal responsible
    for the triggering operation
  end note

  note left of MeldUpdate::getOperation
    Accesses protocol information
    given a relationship type
    (see links to Protocol)
  end note
}

package Protocol {
  class EncodedOperation {
    from : integer
    time : Clock
    pid: IRI
    ...
  }
  note left of EncodedOperation::time
    operation time refers to
    the originating clone. Unlike
    @tick which is always local.
  end note
  EncodedOperation -- Attribution

  class Attribution {
    pid: IRI
    sig?: Buffer
  }
  note left of Attribution::pid
    Not necessarily equal
    to the operation ""pid""
    e.g. if a fusion
  end note

  note left of Attribution::sig
    signature format is app-
    or extension-specific,
    and verifiable as such
  end note

  EncodedOperation o-- "*" EncodedOperation
  note on link
    if ""from"" < ""time.ticks"",
    fused operations from
    a single clone & user.
  end note
}

MeldUpdate o-- "1" EncodedOperation : trigger

MeldUpdate o-- "1" EncodedOperation : applicable

MeldUpdate o-- "0..1" EncodedOperation : resolution

MeldUpdate o-- "*" EncodedOperation : voids

@enduml
